# Site settings
title: Ben Ashford
email:
description: > # this means to ignore newlines until "baseurl:"
  Mildly interesting technology stories.  Clojure, Rust and anything else.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://benashford.github.io"
twitter_username: benashford
github_username:  benashford

permalink: /:categories/:year/:month/:day/:title

production_url: http://benashford.github.io

# Build settings
markdown: kramdown
