(function() {var implementors = {};
implementors["rs_es"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/operations/search/highlight/enum.Encoders.html' title='rs_es::operations::search::highlight::Encoders'>Encoders</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/operations/search/highlight/enum.SettingTypes.html' title='rs_es::operations::search::highlight::SettingTypes'>SettingTypes</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/operations/search/highlight/enum.IndexOptions.html' title='rs_es::operations::search::highlight::IndexOptions'>IndexOptions</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/operations/search/highlight/enum.TermVector.html' title='rs_es::operations::search::highlight::TermVector'>TermVector</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='rs_es/operations/search/highlight/struct.Setting.html' title='rs_es::operations::search::highlight::Setting'>Setting</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='rs_es/operations/search/highlight/struct.Highlight.html' title='rs_es::operations::search::highlight::Highlight'>Highlight</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/query/full_text/enum.MatchType.html' title='rs_es::query::full_text::MatchType'>MatchType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/query/full_text/enum.MatchQueryType.html' title='rs_es::query::full_text::MatchQueryType'>MatchQueryType</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
