(function() {var implementors = {};
implementors['rs_es'] = ["<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/query/enum.ZeroTermsQuery.html' title='rs_es::query::ZeroTermsQuery'>ZeroTermsQuery</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/query/enum.MatchType.html' title='rs_es::query::MatchType'>MatchType</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/query/enum.MatchQueryType.html' title='rs_es::query::MatchQueryType'>MatchQueryType</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/query/enum.ScoreMode.html' title='rs_es::query::ScoreMode'>ScoreMode</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/query/enum.BoostMode.html' title='rs_es::query::BoostMode'>BoostMode</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/query/enum.OptimizeBbox.html' title='rs_es::query::OptimizeBbox'>OptimizeBbox</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/query/enum.Execution.html' title='rs_es::query::Execution'>Execution</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/query/enum.Modifier.html' title='rs_es::query::Modifier'>Modifier</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rs_es/query/enum.MultiValueMode.html' title='rs_es::query::MultiValueMode'>MultiValueMode</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
